kind: Service
apiVersion: v1
metadata:
  name: bonee-themes
  namespace: bonee
  annotations: 
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 
  selector:
    app: bonee-themes
  type: ClusterIP
  sessionAffinity: None